// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5514.DeepSpaceCmdArch.subsystems;

import org.usfirst.frc5514.DeepSpaceCmdArch.Robot;
import org.usfirst.frc5514.DeepSpaceCmdArch.RobotMap;
import org.usfirst.frc5514.DeepSpaceCmdArch.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class HatchExtend extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final Spark extender = RobotMap.hatchExtender;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    	if (Robot.oi.getHandExt()) {
    		System.out.println("Hand Extend button pressed, speed = "+ -1.0*Robot.oi.getSpeed());
    		extender.set(-1.0*Robot.oi.getSpeed());
    		
    	} else if (Robot.oi.getHandRtc()) {
    		System.out.println("Hand Retract button pressed, speed = "+ -1.0*Robot.oi.getSpeed());
    		extender.set(Robot.oi.getSpeed());
    		
    	} else {
    		
    		extender.set(0);
    		
    	}
    	
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

