// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5514.DeepSpaceCmdArch.subsystems;


// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class LineTarget {

	PixyPacket block1, block2;
	double avgWidth;
	double avgHeight;
	double avgArea;
	double avgX;
	double angle;
	double distance;
	
	// Constants
	final double TARGET_X = 160;
	final double DEGREES_PER_PIXEL = 75.0 / 320.0;
	

	public LineTarget (PixyPacket p1, PixyPacket p2) {
		
		block1 = p1;
		block2 = p2;
		
		if (block1 == null && block2 != null)
			block1 = block2;
		else if (block1 != null && block2 == null)
			block2 = block1;
		doMath();
	}
	
	public LineTarget() {
		
		System.out.println("Default Constructors are working");
		
	}
	
	// TODO: add some private functions to do math and stuff to convert data in blocks to distance and angle.
	private void doMath(){
		
		avgWidth = (block1.Width + block2.Width) / 2;
		avgHeight = (block1.Height + block2.Height) / 2;
		avgArea = avgHeight * avgWidth;
		
		avgX = (block1.X + block2.X) / 2;
		angle = (avgX - TARGET_X) * DEGREES_PER_PIXEL;
		
		distance = 106.83987509669 * Math.pow(.96060468112129, avgHeight);
	}
	

	public double distance() {
		// return distance needed to drive to hang gear.
		return distance;
	}
	
	public double angle() {
		// return angle needed to turn robot to line up with gear peg
		return angle; //X distance in pixels converted to degrees
	}
	
	public String toString() {
		
		return "" +
	"avgWidth: " + avgWidth + 
	" avgHeight: " + avgHeight +
	" avgArea: " + avgArea +
	" avgX: " + avgX +
	" dpp: " + DEGREES_PER_PIXEL +
	" angle: " + angle +
	" distance: " + distance;
	}

}

